<?php

    function caesar_cipher_menu()
    {
        $items = array();
        $items['caesar_cipher'] = array(
            'title' => 'Caesar Cipher',
            'page callback' => 'drupal_get_form',
            'page arguments' => array('caesar_cipher_form'),
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
        );

        $items['caesar_cipher_result_page'] = array(
            'title' => 'Caesar Cipher Results',
            'page callback' => 'caesar_cipher_result',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        );
        return $items;
    }

    function caesar_cipher_form()
    {
        $form['shift_value'] = array(
            '#title' => 'Shift Value',
            '#type' => 'textfield',
            '#description' => t('Please enter the number of places you want to shift each letter.'),
            '#element_validate' => array('element_validate_positive_integer'),
            '#required' => TRUE,
        );

        $form['shift_direction'] = array(
            '#title' => 'Shift Direction',
            '#type' => 'textfield',
            '#description' => t('Would you like to shift to the right or to the left?'),
            '#element_validate' => array('element_validate_positive_integer', 'direction_validate'),
            '#required' => TRUE,
        );

        $form['phrase'] = array(
            '#title' => 'Phrase',
            '#type' => 'textfield',
            '#description' => t('Please enter the phrase you would like encoded.'),
            '#element_validate' => array('element_validate_positive_integer'),
            '#required' => TRUE,
        );

        $form['submit'] = array(
            '#type' => 'submit',
            '#value' => 'Submit',
        );

        return $form;
    }

    function direction_validate($element)
    {
        $user_direction = $element['#value'];

        if ($user_direction != 'Right' || 'right' || 'Left' || 'left'){
            return "Please enter either Left or Right";
        }

    }
