<?php

    function caesar_cipher_menu()
    {
        $items = array();
        $items['caesar_cipher'] = array(
            'title' => 'Caesar Cipher',
            'page callback' => 'drupal_get_form',
            'page arguments' => array('caesar_cipher_form'),
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
        );

        $items['caesar_cipher_result'] = array(
            'title' => 'Caesar Cipher Results',
            'page callback' => 'caesar_cipher_result',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        );
        return $items;
    }

    function caesar_cipher_form()
    {
        $form['shift_value'] = array(
            '#title' => 'Shift Value',
            '#type' => 'textfield',
            '#description' => t('Please enter the number of places you want to shift each letter.'),
            '#element_validate' => array('element_validate_integer_positive'),
            '#required' => TRUE,
        );

        $form['shift_direction'] = array(
            '#title' => 'Shift Direction',
            '#type' => 'textfield',
            '#description' => t('Would you like to shift to the right or to the left?'),
            '#element_validate' => array('direction_validate'),
            '#required' => TRUE,
        );

        $form['phrase'] = array(
            '#title' => 'Phrase',
            '#type' => 'textfield',
            '#description' => t('Please enter the phrase you would like encoded.'),
            // '#element_validate' => array(),
            '#required' => TRUE,
        );

        $form['submit'] = array(
            '#type' => 'submit',
            '#value' => 'Submit',
        );

        return $form;
    }

    function direction_validate($element)
    {
        $user_direction = $element['#value'];
        drupal_set_message($user_direction);
        if (($user_direction != 'Right') && ($user_direction != 'right') && ($user_direction != 'Left') && ($user_direction != 'left')){
            form_error($element, t("Please enter either Left or Right"));
        }
    }

    function caesar_cipher_form_submit($form, &$form_state)
    {
        $shift_value = $form_state['values']['shift_value'];
        $shift_direction = $form_state['values']['shift_direction'];
        $phrase = $form_state['values']['phrase'];

        $_SESSION['encoded_result'] = 'Thank you. Your shift value is ' . $shift_value . ' and your shift direction is ' . $shift_direction . '. Your encoded phrase is ' . $phrase . '.';

        $form_state['redirect'] = 'caesar_cipher_result';
    }

    function caesar_cipher_result()
    {
        $answer = $_SESSION['encoded_result'];
        return $answer;
    }
